# General settings
max_workers: 4
progress_update_frequency: 10
report_format: 'markdown'

# Scraper settings
user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
max_scrolls: 5
scroll_pause_time: 2.0
delay_min: 1
delay_max: 3

# Postprocessor settings
supported_file_types:
  - '.txt'
  - '.md'
  - '.html'
max_file_size: 10485760  # 10 MB in bytes

# LinkExtractor settings
max_links: 100

# Gradio interface settings
theme: 'default'